module.exports = {
  LOG: 'LOG',
  ADD_HEADER: 'ADD_HEADER',
  PUBLISH: 'PUBLISH',
  FINALIZE: 'FINALIZE',
  INIT: 'INIT',
  ATTACH: 'ATTACH',
  TRACE: 'TRACE',
  EXTEND: 'EXTEND',
  START_TRACE: 'START_TRACE',
  END_TRACE: 'END_TRACE',
};
